/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualfront;
import appinfo.AppInfo;
import filecontrol.VideogameFileControl;
import java.util.ArrayList;
import date.Date;
import videogame.Videogame;
import datacontrol.DataControl;
/**
 * Investigar sobre JDialog.
 * @author Alex Guirao Lopez <aguiraol2021@cepnet.net>
 */
public class AddElement extends javax.swing.JFrame {

    private static int counter=0;
    
    public AddElement() {
        initComponents();
        setTitle(AppInfo.name);
        setVisible(true);
        setLocationRelativeTo(null);
    }

    public void showList(){
        for (Videogame v:DataControl.gameList){
            System.out.println(v.toString());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGameConsole = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        txtMonth = new javax.swing.JTextField();
        txtDay = new javax.swing.JTextField();
        btnLeftArrow = new javax.swing.JButton();
        btnRightArrow = new javax.swing.JButton();
        lblGameTitle = new javax.swing.JLabel();
        lblGameCompany = new javax.swing.JLabel();
        lblGameConsole = new javax.swing.JLabel();
        lblGameReleaseDate = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Titulo");

        jLabel2.setText("Empresa");

        jLabel3.setText("Consola");

        jLabel4.setText("Lanzamiento");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("INTRODUCE UN VIDEOJUEGO");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnLeftArrow.setText("<==");
        btnLeftArrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftArrowActionPerformed(evt);
            }
        });

        btnRightArrow.setText("==>");
        btnRightArrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRightArrowMouseClicked(evt);
            }
        });

        lblGameTitle.setText("jLabel6");

        lblGameCompany.setText("jLabel7");

        lblGameConsole.setText("jLabel8");

        lblGameReleaseDate.setText("jLabel9");

        btnRegister.setText("Record Data");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtGameConsole, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCompany, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitle, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLeftArrow)
                        .addGap(91, 91, 91)
                        .addComponent(btnRightArrow)
                        .addGap(141, 141, 141))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGameCompany)
                            .addComponent(lblGameTitle)
                            .addComponent(lblGameConsole)
                            .addComponent(lblGameReleaseDate))
                        .addContainerGap(216, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGameTitle)
                        .addGap(18, 18, 18)
                        .addComponent(lblGameCompany)
                        .addGap(19, 19, 19)
                        .addComponent(lblGameConsole)
                        .addGap(18, 18, 18)
                        .addComponent(lblGameReleaseDate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGameConsole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLeftArrow)
                    .addComponent(btnRightArrow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        txtTitle.getAccessibleContext().setAccessibleName("txtTitle");
        txtCompany.getAccessibleContext().setAccessibleName("txtCompany");
        txtGameConsole.getAccessibleContext().setAccessibleName("txtGameConsole");
        txtYear.getAccessibleContext().setAccessibleName("txtYear");
        btnCancel.getAccessibleContext().setAccessibleName("btnRecord");
        txtMonth.getAccessibleContext().setAccessibleName("txtMonth");
        txtDay.getAccessibleContext().setAccessibleName("txtDay");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
        new MainWindow();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * Añade un videojuego a la lista local. (Datos no persistentes)
     * @throws NumberFormatException 
     */
    private void addVideogame() throws NumberFormatException {
        String title=txtTitle.getText();
        String company=txtCompany.getText();
        String gameConsole=txtGameConsole.getText();
        int year=Integer.parseInt(txtYear.getText());
        int month=Integer.parseInt(txtMonth.getText());
        int day=Integer.parseInt(txtDay.getText());
        
        DataControl.gameList.add(new Videogame(title, company, gameConsole, new Date (year,month,day)));
        
        txtTitle.setText("");
        txtCompany.setText("");
        txtGameConsole.setText("");
        txtDay.setText("");
        txtYear.setText("");
        txtMonth.setText("");
        
        MainWindow mw = new MainWindow();
        setVisible(false);
        //DEBUG
        System.out.println(ConsoleColors.GREEN+"¡El videojuego se registró con éxito!");
        showList();
    }

    private void btnRightArrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRightArrowMouseClicked
        if(DataControl.gameList.size()>counter)
        { 
            lblGameTitle.setText(DataControl.gameList.get(counter).getTitle());
            lblGameCompany.setText(DataControl.gameList.get(counter).getCompany());
            lblGameConsole.setText(DataControl.gameList.get(counter).getGameConsole());
            lblGameReleaseDate.setText(DataControl.gameList.get(counter).getReleaseDate().toString());
            counter++;
            
            //DEBUG
            System.out.println("Counter: "+counter);
        }
    }//GEN-LAST:event_btnRightArrowMouseClicked

    private void btnLeftArrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftArrowActionPerformed
         if(counter!=0)
        { 
            counter--;
            
            lblGameTitle.setText(DataControl.gameList.get(counter).getTitle());
            lblGameCompany.setText(DataControl.gameList.get(counter).getCompany());
            lblGameConsole.setText(DataControl.gameList.get(counter).getGameConsole());
            lblGameReleaseDate.setText(DataControl.gameList.get(counter).getReleaseDate().toString());
            
             //DEBUG
            System.out.println("Counter: "+counter);
        }
    }//GEN-LAST:event_btnLeftArrowActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        addVideogame();
    }//GEN-LAST:event_btnRegisterActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLeftArrow;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRightArrow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblGameCompany;
    private javax.swing.JLabel lblGameConsole;
    private javax.swing.JLabel lblGameReleaseDate;
    private javax.swing.JLabel lblGameTitle;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtGameConsole;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
