package visualfront;

import appinfo.AppInfo;
import database.Database;
import datacontrol.DataControl;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import user.User;
/**
 * @author Alex Guirao Lopez <aguiraol2021@cepnet.net>
 */
public class Login extends javax.swing.JFrame {
    
    public Login()
    {
        initComponents();
        setLocationRelativeTo(null);
        setTitle(AppInfo.NAME);
        setIconImage(WindowControl.appIcon.getImage());
        ImageIcon backgroundImage = new ImageIcon("assets/bckgImage/arcadeMachineBackground.jpg");
        JLabel background = new JLabel("",backgroundImage,JLabel.CENTER);
        background.setBounds(0, 0, 500, 500);
        add(background);
        txtError.setVisible(false);
        setResizable(true);
        setVisible(true);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        txtError = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnForgot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("USERNAME");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("PASSWORD");

        btnEnter.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnEnter.setText("Enter");
        btnEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEnterMousePressed(evt);
            }
        });

        txtError.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtError.setForeground(new java.awt.Color(255, 0, 0));
        txtError.setText("jLabel2");

        jButton1.setText("New User");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnForgot.setText("Forgot your password?");
        btnForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnForgotMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtError)
                                .addGap(10, 10, 10)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnForgot, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtError)
                .addGap(30, 30, 30)
                .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnForgot))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        AddUser au = new AddUser(this,true);
    }//GEN-LAST:event_jButton1MousePressed

    private void btnEnterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMousePressed
        /*EN ARCHIVO BINARIO
        boolean userExists=false;
        String userName = txtUsername.getText();
        String password = txtPass.getText();
        
        for (User u:DataControl.userList)
        {
            if (userName.equals(u.getUsername())&&password.equals(u.getPassword()))
            {
                userExists=true;
            }
        }
        
        if (userExists)
        {
            new MainWindow();
            setVisible(false);
        }else{
            txtError.setVisible(true);
            txtError.setText("User does not exist");
            txtUsername.setText("");
            txtPass.setText("");
        }
        */
        
        //EN BASE DE DATOS
        String userName = txtUsername.getText();
        String password = txtPass.getText();
        
        try {
            Database db = new Database();
            if (db.checkUserExist(userName))
            {
                if (db.checkUserPassword(userName, password))
                {
                    new MainWindow();
                    setVisible(false);
                }else{
                    txtError.setVisible(true);
                    txtError.setText("Password does not match");
                }
            }else{
                txtError.setVisible(true);
                txtError.setText("Username does not exists");
            }
            
            db.close();
        } 
        catch (SQLException ex) 
        {
            System.out.println(ConsoleColors.RED+"No se pudo acceder a la base de datos");
        }
        
        
    }//GEN-LAST:event_btnEnterMousePressed

    private void btnForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnForgotMouseClicked
        new ForgotPassword(this, true);
    }//GEN-LAST:event_btnForgotMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnForgot;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel txtError;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
